"""empty message

Revision ID: 49ad5f1d8619
Revises: b380b9185ef1
Create Date: 2016-04-10 15:08:53.392675

"""

# revision identifiers, used by Alembic.
revision = '49ad5f1d8619'
down_revision = 'b380b9185ef1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
