"""empty message

Revision ID: 5d5d1b0112ae
Revises: 
Create Date: 2016-04-10 15:03:34.870947

"""

# revision identifiers, used by Alembic.
revision = '5d5d1b0112ae'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
