"""empty message

Revision ID: b380b9185ef1
Revises: 5d5d1b0112ae
Create Date: 2016-04-10 15:03:52.887959

"""

# revision identifiers, used by Alembic.
revision = 'b380b9185ef1'
down_revision = '5d5d1b0112ae'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
